In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/marinedatap1/marinedata_train.csv
/kaggle/input/marinedatap1/marinedata_test.csv
/kaggle/input/marinedatap1/marinedata_val.csv
/kaggle/input/centerdirectory3/marinedata_val.pkl
/kaggle/input/centerdirectory3/marinedata_train.pkl
/kaggle/input/centerdirectory3/marinedata_test.pkl

In [2]:
# Note: Preprocessing already complete
dataTrain = pd.read_csv("/kaggle/input/marinedatap1/marinedata_train.csv")
dataVal = pd.read_csv("/kaggle/input/marinedatap1/marinedata_val.csv")
dataTest = pd.read_csv("/kaggle/input/marinedatap1/marinedata_test.csv")

In [3]:
dataTrain.head()

,timestamp,mmsi,lat,lon,speed,heading,timePassed,timeStep,path,timePassedTotal,torque,alat,alon,aspeed,aheading,pathIni
0,2017-12-22 10:23:57,205366000,57.756818,10.420237,9.16,79.0,4316690,1973822,4,1513938237,0,0.340376,0.048352,0.1832,0.219444,0
1,2017-12-22 10:34:03,205366000,57.767407,10.509043,8.90,79.0,4317296,606,4,1513938843,0,0.341204,0.052561,0.1780,0.219444,0
2,2017-12-22 10:45:13,205366000,57.777053,10.594123,8.18,85.0,4317966,670,4,1513939513,0,0.341957,0.056594,0.1636,0.236111,0
3,2017-12-22 10:55:19,205366000,57.776770,10.678505,8.33,93.0,4318572,606,4,1513940119,0,0.341935,0.060593,0.1666,0.258333,0
4,2017-12-22 11:04:30,205366000,57.768455,10.734610,3.55,163.0,4319123,551,4,1513940670,0,0.341286,0.063252,0.0710,0.452778,0

In [4]:
# transformer output given here (note: model was only run a few epochs, 
# results may be kinda garbage)
checker = pd.DataFrame([[0.5315, 0.4595, 0.1574, 0.9028],
         [0.5343, 0.4571, 0.1554, 0.9306],
         [0.5374, 0.4560, 0.1564, 0.9750],
         [0.5408, 0.4557, 0.1574, 0.0083],
         [0.5440, 0.4558, 0.1574, 0.0000],
         [0.5473, 0.4556, 0.1564, 0.9972],
         [0.5506, 0.4555, 0.1564, 0.0000],
         [0.5539, 0.4555, 0.1564, 0.0028],
         [0.5560, 0.4549, 0.1554, 0.9528],
         [0.5587, 0.4538, 0.1554, 0.9528],
         [0.5607, 0.4530, 0.1554, 0.9528],
         [0.5633, 0.4520, 0.1554, 0.9528],
         [0.5654, 0.4511, 0.1564, 0.9528],
         [0.5680, 0.4500, 0.1564, 0.9528],
         [0.5727, 0.4480, 0.1554, 0.9500],
         [0.5758, 0.4467, 0.1554, 0.9500],
         [0.5789, 0.4454, 0.1544, 0.9500],
         [0.5821, 0.4441, 0.1534, 0.9500],
         [0.5860, 0.4426, 0.1500, 0.9375],
         [0.5900, 0.4426, 0.1500, 0.9375],
         [0.6020, 0.4426, 0.1500, 0.9375],
         [0.6060, 0.4426, 0.1500, 0.9514],
         [0.6060, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6140, 0.4426, 0.1500, 0.9514],
         [0.6060, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.9653],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6060, 0.4426, 0.1500, 0.9514],
         [0.6060, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6140, 0.4426, 0.1500, 0.9375],
         [0.6140, 0.4426, 0.1500, 0.9375],
         [0.6140, 0.4426, 0.1500, 0.9236],
         [0.6180, 0.4426, 0.1500, 0.9236],
         [0.6180, 0.4389, 0.1500, 0.9236],
         [0.6180, 0.4389, 0.1500, 0.7153],
         [0.6020, 0.4315, 0.1500, 0.7153],
         [0.6020, 0.4278, 0.1500, 0.7153]], columns=["alat", "alon", "aspeed", "aheading"])
checker.head()

     alat    alon  aspeed  aheading
0  0.5315  0.4595  0.1574    0.9028
1  0.5343  0.4571  0.1554    0.9306
2  0.5374  0.4560  0.1564    0.9750
3  0.5408  0.4557  0.1574    0.0083
4  0.5440  0.4558  0.1574    0.0000

In [5]:
from sklearn.ensemble import IsolationForest

X = dataTrain[["alat", "alon", "aspeed", "aheading"]]

clf = IsolationForest(contamination = 0.01, bootstrap=True, n_jobs=-1, random_state=42).fit(X)
array = clf.predict(checker)

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

In [6]:
print(array)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1]

In [7]:
# I changed the data to create an anomaly
anomaly = pd.DataFrame([[0.8000, 0.2695, 0.1740, 0.0280],
         [0.1343, 0.4571, 0.1554, 0.9306],
         [0.2374, 0.4560, 0.1564, 0.9750],
         [0.3408, 0.4557, 0.1574, 0.0083],
         [0.4440, 0.4558, 0.1574, 0.0000],
         [0.5473, 0.4556, 0.1564, 0.9972],
         [0.6506, 0.4555, 0.1564, 0.0000],
         [0.7539, 0.4555, 0.1564, 0.0028],
         [0.8560, 0.4549, 0.2554, 0.9528],
         [0.9587, 0.2538, 0.1554, 0.9528],
         [0.5607, 0.1530, 0.1554, 0.9528],
         [0.5633, 0.5520, 0.1554, 0.9528],
         [0.5654, 0.9511, 0.1564, 0.9528],
         [0.5680, 0.0500, 0.1564, 0.9528],
         [0.5727, 0.6480, 0.1554, 0.9500],
         [0.5758, 0.9467, 0.1554, 0.9500],
         [0.5789, 0.4454, 0.5544, 0.9500],
         [0.5821, 0.4441, 0.1534, 0.9500],
         [0.5860, 0.4426, 0.1500, 0.9375],
         [0.5900, 0.4426, 0.1500, 0.9375],
         [0.6020, 0.4426, 0.6500, 0.9375],
         [0.6060, 0.4426, 0.1500, 0.5514],
         [0.6060, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.5514],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6140, 0.4426, 0.1500, 0.9514],
         [0.6060, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.9653],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6060, 0.4426, 0.1500, 0.9514],
         [0.6060, 0.4426, 0.1500, 0.9514],
         [0.6100, 0.4426, 0.1500, 0.9514],
         [0.6140, 0.4426, 0.1500, 0.7375],
         [0.6140, 0.4426, 0.1500, 0.9375],
         [0.6140, 0.4426, 0.1500, 0.9236],
         [0.6180, 0.4426, 0.1500, 0.1236],
         [0.6180, 0.4389, 0.1500, 0.9236],
         [0.6180, 0.4389, 0.1500, 0.2153],
         [0.9020, 0.2315, 0.5000, 0.2153],
         [0.6020, 0.4278, 0.1500, 0.7153]], columns=["alat", "alon", "aspeed", "aheading"])
anomaly.head()

     alat    alon  aspeed  aheading
0  0.8000  0.2695  0.1740    0.0280
1  0.1343  0.4571  0.1554    0.9306
2  0.2374  0.4560  0.1564    0.9750
3  0.3408  0.4557  0.1574    0.0083
4  0.4440  0.4558  0.1574    0.0000

In [8]:
arrayAnom = clf.predict(anomaly)
print(arrayAnom)

[-1  1  1  1  1  1  1  1 -1 -1  1  1 -1  1  1 -1 -1  1  1  1 -1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1]

All the points I switched were changed to -1, this may not be representative of a true anomaly in a real-world setting, but at the very least, this shows that deviations from a normal set of data points will be detected (and this also implies that the transformer model is working, at least well enough that the isolation forest believes that the predicted model is a set of real points.